//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class Apply_New_Request {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox info;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.Button ConfirmButton;
	}
}
