//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class contributorpart4 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.GridView table1;
		
		protected System.Web.UI.WebControls.LinkButton linkselect;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.Button Button5;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Button Button6;
		
		protected System.Web.UI.WebControls.Button Button7;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.Label Label5;
	}
}
