//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class Create_Event {
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.TextBox Description;
		
		protected System.Web.UI.WebControls.TextBox Location;
		
		protected System.Web.UI.WebControls.TextBox City;
		
		protected System.Web.UI.WebControls.TextBox Time;
		
		protected System.Web.UI.WebControls.TextBox Entertainer;
		
		protected System.Web.UI.WebControls.TextBox Photo;
		
		protected System.Web.UI.WebControls.TextBox Video;
		
		protected System.Web.UI.WebControls.CheckBox CheckBoxAD;
		
		protected System.Web.UI.WebControls.Button Confirm;
	}
}
