//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button login_button;
		
		protected System.Web.UI.WebControls.Button register_button;
		
		protected System.Web.UI.WebControls.Button deactivate_button;
		
		protected System.Web.UI.WebControls.Button view_button;
		
		protected System.Web.UI.WebControls.Button edit_button;
		
		protected System.Web.UI.WebControls.TextBox search_content_category;
		
		protected System.Web.UI.WebControls.TextBox search_content_type;
		
		protected System.Web.UI.WebControls.Button search_content_button;
		
		protected System.Web.UI.WebControls.Label search_content_label;
		
		protected System.Web.UI.WebControls.GridView search_content_results;
		
		protected System.Web.UI.WebControls.TextBox search_contributors_name;
		
		protected System.Web.UI.WebControls.Button search_contributors_button;
		
		protected System.Web.UI.WebControls.Label search_contributors_label;
		
		protected System.Web.UI.WebControls.GridView search_contributors_results;
		
		protected System.Web.UI.WebControls.Button show_contributors_button;
		
		protected System.Web.UI.WebControls.Label show_contributors_label;
		
		protected System.Web.UI.WebControls.GridView show_contributors_results;
		
		protected System.Web.UI.WebControls.TextBox show_original_content;
		
		protected System.Web.UI.WebControls.Button show_original_content_button;
		
		protected System.Web.UI.WebControls.Label show_original_content_label;
		
		protected System.Web.UI.WebControls.GridView show_original_content_results;
	}
}
