//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class EditProfile {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox edit_email;
		
		protected System.Web.UI.WebControls.TextBox edit_password;
		
		protected System.Web.UI.WebControls.TextBox edit_firstname;
		
		protected System.Web.UI.WebControls.TextBox edit_middlename;
		
		protected System.Web.UI.WebControls.TextBox edit_lastname;
		
		protected System.Web.UI.WebControls.TextBox edit_birth_year;
		
		protected System.Web.UI.WebControls.TextBox edit_birth_month;
		
		protected System.Web.UI.WebControls.TextBox edit_birth_day;
		
		protected System.Web.UI.WebControls.TextBox edit_working_place_name;
		
		protected System.Web.UI.WebControls.TextBox edit_working_place_type;
		
		protected System.Web.UI.WebControls.TextBox edit_wokring_place_description;
		
		protected System.Web.UI.WebControls.TextBox edit_specilization;
		
		protected System.Web.UI.WebControls.TextBox edit_portofolio_link;
		
		protected System.Web.UI.WebControls.TextBox edit_years_experience;
		
		protected System.Web.UI.WebControls.TextBox edit_hire_year;
		
		protected System.Web.UI.WebControls.TextBox edit_hire_month;
		
		protected System.Web.UI.WebControls.TextBox edit_hire_day;
		
		protected System.Web.UI.WebControls.TextBox edit_working_hours;
		
		protected System.Web.UI.WebControls.TextBox edit_payment_rate;
		
		protected System.Web.UI.WebControls.Button do_edit_button;
		
		protected System.Web.UI.WebControls.Button BackButton;
	}
}
