//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class login {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox login_email;
		
		protected System.Web.UI.WebControls.TextBox login_password;
		
		protected System.Web.UI.WebControls.Button do_login_button;
		
		protected System.Web.UI.WebControls.Button back_to_register_button;
		
		protected System.Web.UI.WebControls.Button BackButton;
	}
}
