//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class Register {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList register_userType;
		
		protected System.Web.UI.WebControls.TextBox register_email;
		
		protected System.Web.UI.WebControls.TextBox register_password;
		
		protected System.Web.UI.WebControls.TextBox register_firstname;
		
		protected System.Web.UI.WebControls.TextBox register_middlename;
		
		protected System.Web.UI.WebControls.TextBox register_lastname;
		
		protected System.Web.UI.WebControls.TextBox register_birth_year;
		
		protected System.Web.UI.WebControls.TextBox register_birth_month;
		
		protected System.Web.UI.WebControls.TextBox register_birth_day;
		
		protected System.Web.UI.WebControls.TextBox register_working_place_name;
		
		protected System.Web.UI.WebControls.TextBox register_working_place_type;
		
		protected System.Web.UI.WebControls.TextBox register_wokring_place_description;
		
		protected System.Web.UI.WebControls.TextBox register_specilization;
		
		protected System.Web.UI.WebControls.TextBox register_portofolio_link;
		
		protected System.Web.UI.WebControls.TextBox register_years_experience;
		
		protected System.Web.UI.WebControls.TextBox register_hire_year;
		
		protected System.Web.UI.WebControls.TextBox register_hire_month;
		
		protected System.Web.UI.WebControls.TextBox register_hire_day;
		
		protected System.Web.UI.WebControls.TextBox register_working_hours;
		
		protected System.Web.UI.WebControls.TextBox register_payment_rate;
		
		protected System.Web.UI.WebControls.Button do_register_button;
		
		protected System.Web.UI.WebControls.Button back_to_login_button;
		
		protected System.Web.UI.WebControls.Button BackButton;
	}
}
