//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEgypt {
	
	
	public partial class ViewProfile {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label userType_label;
		
		protected System.Web.UI.WebControls.GridView view_results;
		
		protected System.Web.UI.WebControls.Button show_more_button;
		
		protected System.Web.UI.WebControls.Button BackButton;
	}
}
